//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Web.Administration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Web.Administration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                      
        ///&lt;!--
        ///
        ///    .NET Framework configuration schema (beyond ASP.NET).
        ///    
        ///    Please do not edit this file. To add configuration sections to the schema,
        ///    put them in .xml files similar to this one, in this directory. They will
        ///    be picked up automatically at application pool startup.
        ///
        ///--&gt;
        ///&lt;configSchema&gt;
        ///    &lt;sectionSchema name=&quot;appSettings&quot;&gt;
        ///        &lt;attribute name=&quot;file&quot; type=&quot;string&quot; /&gt;
        ///        &lt;collection addElement=&quot;add&quot; removeElement=&quot;remove&quot; clearElement=&quot;clear&quot;&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FX_schema {
            get {
                return ResourceManager.GetString("FX_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///
        ///    IIS configuration schema.
        ///
        ///    Please do not edit this file. To add configuration sections to the schema,
        ///    put them in .xml files similar to this one, in this directory. They will
        ///    be picked up automatically at application pool startup.
        ///
        ///--&gt;
        ///
        ///&lt;configSchema&gt;
        ///
        ///  &lt;!--
        ///
        ///    The schema for each configuration section is defined in a &lt;sectionSchema&gt;
        ///    XML element. There is no schema definition for section groups.
        ///
        ///    The following format is used to document the schema:
        ///    &lt;att [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IIS_schema {
            get {
                return ResourceManager.GetString("IIS_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!--
        ///
        ///    IIS configuration sections.
        ///
        ///    For schema documentation, see
        ///    %IIS_BIN%\config\schema\IIS_schema.xml.
        ///    
        ///    Please make a backup of this file before making any changes to it.
        ///
        ///    NOTE: The following environment variables are available to be used
        ///          within this file and are understood by the IIS Express.
        ///
        ///          %IIS_USER_HOME% - The IIS Express home directory for the user
        ///          %IIS_SITES_HOME% - The default home directory [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string original {
            get {
                return ResourceManager.GetString("original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///    
        ///    IIS URL Rewrite configuration schema.
        ///    
        ///    ** Please DO NOT edit this file yourself. **
        ///    
        ///    If you want to add configuration sections to the schema, you may place 
        ///    them in .xml files similar to this one, in this directory. They will be 
        ///    picked up automatically on startup.
        ///
        ///--&gt;
        ///
        ///&lt;configSchema&gt;
        ///  &lt;sectionSchema name=&quot;system.webServer/rewrite/globalRules&quot;&gt;
        ///    &lt;collection addElement=&quot;rule&quot; clearElement=&quot;clear&quot; removeElement=&quot;remove&quot;&gt;
        ///      &lt;attribute name=&quot;name&quot; ty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rewrite_schema {
            get {
                return ResourceManager.GetString("rewrite_schema", resourceCulture);
            }
        }
    }
}
