// Copyright (c) Lex Li. All rights reserved.
//
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace JexusManager.AppCmd
{
    public static class HelpTexts
    {
        public const string StopSite = "Stop virtual site\r\n\r\r\nAPPCMD stop SITE <identifier> <-parameter1:value1 ...>\r\r\n\r\r\nStops the specified virtual site, and prevents new requests from being\r\nreceived on its binding endpoints. The exact site identifier must be provided\r\nand must resolve to an existing site.\r\n \r\r\nSupported parameters:\r\r\n\r\r\n identifier (required)\r\n\r\n    Site name or url of the site to stop\r\n\r\n /site.name\r\n\r\n    Site name or url of the site to stop (same as identifier)\r\n\r\n\r\r\nExamples:\r\r\n\r\r\n appcmd stop site \"Default Web Site\"\r\n\r\n    Stop the site \"Default Web Site\".\r\n\r\n";

        public const string Vdir = "Administration of virtual directories\r\r\n\r\r\nAPPCMD (command) VDIR <identifier> <-parameter1:value1 ...>\r\r\n\r\r\nSupported commands:\r\r\n\r\r\n  list      List virtual directories\r\n  set       Configure virtual directory\r\n  add       Add new virtual directory\r\n  delete    Delete virtual directory\r\n\r\r\n(To get help for each command use /?, e.g. 'appcmd.exe add site /?'.)\r\r\n";

        public const string StartAppPool = "Start application pool\r\n\r\r\nAPPCMD start APPPOOL <identifier> <-parameter1:value1 ...>\r\r\n\r\r\nStarts the specified application pool, allowing new worker processes running\r\nthe applications in this application pool to be started.  The exact\r\napplication pool identifier must be provided and must resolve to an existing\r\napplication pool.\r\n \r\r\nSupported parameters:\r\r\n\r\r\n identifier (required)\r\n\r\n    Application pool name of the application pool to start\r\n\r\n /apppool.name\r\n\r\n    Application pool name of the application pool to start (same as\r\n    identifier)\r\n\r\n /wait\r\n\r\n    Whether the command should wait for the application pool to start before\r\n    returning\r\n\r\n /timeout\r\n\r\n    How long to wait for the application pool to start (milliseconds).  Only\r\n    valid when waiting is enabled\r\n\r\n\r\r\nExamples:\r\r\n\r\r\n appcmd start apppool \"MyAppPool\"\r\n\r\n    Start the application pool \"MyAppPool\".\r\n\r\n";

        public const string App = "Administration of applications\r\r\n\r\r\nAPPCMD (command) APP <identifier> <-parameter1:value1 ...>\r\r\n\r\r\nSupported commands:\r\r\n\r\r\n  list      List applications\r\n  set       Configure application\r\n  add       Add new application\r\n  delete    Delete application\r\n\r\r\n(To get help for each command use /?, e.g. 'appcmd.exe add site /?'.)\r\r\n";

        public const string ListAppPool = "List application pools\r\n\r\r\nAPPCMD list APPPOOL <identifier> <-parameter1:value1 ...>\r\r\n\r\r\nList the application pools on the machine.  This command can be used to find a\r\nspecific application pool by using its identifier, or match zero or more\r\napplication pools based on the specified application pool attributes.\r\n \r\r\nSupported parameters:\r\r\n\r\r\n identifier\r\n\r\n    Application pool name of the application pool to find\r\n\r\n /apppool.name\r\n\r\n    Application pool name of the application pool to find (same as\r\n    identifier)\r\n\r\n /?\r\n\r\n    Display the dynamic properties that can be used to find one or more\r\n    application pool objects\r\n\r\n\r\r\nExamples:\r\r\n\r\r\n appcmd list apppools\r\n\r\n    List all application pools on the machine.\r\n\r\n appcmd list apppool \"DefaultAppPool/\"\r\n\r\n    Find the application pool \"DefaultAppPool\".\r\n\r\n appcmd list apppools /autoStart:true /processModel.loadUserProfile:false\r\n\r\n    Find all application pools that have the \"autoStart\" and\r\n    \"processModel.loadUserProfile\" configuration properties set to the\r\n    specified values.\r\n\r\n";

        public const string StopAppPool = "Stop application pool\r\n\r\r\nAPPCMD stop APPPOOL <identifier> <-parameter1:value1 ...>\r\r\n\r\r\nStops the specified application pool, shutting down existing worker processes\r\nrunning the applications in this application pool, and preventing new worker\r\nprocesses from being started.  The exact application pool identifier must be\r\nprovided and must resolve to an existing application pool.\r\n \r\r\nSupported parameters:\r\r\n\r\r\n identifier (required)\r\n\r\n    Application pool name of the application pool to stop\r\n\r\n /apppool.name\r\n\r\n    Application pool name of the application pool to stop (same as\r\n    identifier)\r\n\r\n /wait\r\n\r\n    Whether the command should wait for the application pool to start before\r\n    returning\r\n\r\n /timeout\r\n\r\n    How long to wait for the application pool to start (milliseconds).  Only\r\n    valid when waiting is enabled\r\n\r\n\r\r\nExamples:\r\r\n\r\r\n appcmd stop apppool \"MyAppPool\"\r\n\r\n    Stop the application pool \"MyAppPool\".\r\n\r\n";

        public const string AppPool = "Administration of application pools\r\r\n\r\r\nAPPCMD (command) APPPOOL <identifier> <-parameter1:value1 ...>\r\r\n\r\r\nSupported commands:\r\r\n\r\r\n  list      List application pools\r\n  set       Configure application pool\r\n  add       Add new application pool\r\n  delete    Delete application pool\r\n  start     Start application pool\r\n  stop      Stop application pool\r\n  recycle   Recycle application pool\r\n\r\r\n(To get help for each command use /?, e.g. 'appcmd.exe add site /?'.)\r\r\n";

        public const string Usage = "General purpose IIS command line administration tool.\r\r\n\r\r\nAPPCMD (command) (object-type) <identifier> </parameter1:value1 ...>\r\r\n\r\r\nSupported object types:\r\r\n\r\r\n  SITE      Administration of virtual sites\r\n  APP       Administration of applications\r\n  VDIR      Administration of virtual directories\r\n  APPPOOL   Administration of application pools\r\n  CONFIG    Administration of general configuration sections\r\n  WP        Administration of worker processes\r\n  REQUEST   Administration of HTTP requests\r\n  MODULE    Administration of server modules\r\n  BACKUP    Administration of server configuration backups\r\n  TRACE     Working with failed request trace logs\r\n  BINDING   Object for working with SSL bindings\r\n\r\r\n(To list commands supported by each object use /?, e.g. 'appcmd.exe site /?')\r\r\n\r\r\nGeneral parameters:\r\r\n\r\r\n/?               Display context-sensitive help message.\r\r\n\r\r\n/text<:value>    Generate output in text format (default).\r\r\n                 /text:* shows all object properties in detail view.\r\r\n                 /text:<attribute> shows the value of the specified\r\r\n                 attribute for each object.\r\r\n/xml             Generate output in XML format.\r\r\n                 Use this to produce output that can be sent to another\r\r\n                 command running in /in mode.\r\r\n/in or -         Read and operate on XML input from standard input.\r\r\n                 Use this to operate on input produced by another\r\r\n                 command running in /xml mode.\r\r\n/config<:*>      Show configuration for displayed objects.\r\r\n                 /config:* also includes inherited configuration.\r\r\n/metadata        Show configuration metadata when displaying configuration.\r\r\n\r\r\n/commit          Set config path where configuration changes are saved.\r\r\n                 Can specify either a specific configuration path, \"site\",\r\r\n                 \"app\", \"parent\", or \"url\" to save to the appropriate portion\r\r\n                 of the path being edited by the command, \"apphost\", \"webroot\",\r\r\n                 or \"machine\" for the corresponding configuration level.\r\r\n/apphostconfig   Specify an alternate applicationHost.config file to edit.\r\r\n/debug           Show debugging information for command execution.\r\r\n\r\r\nUse \"!\" to escape parameters that have same names as the general parameters,\r\r\nlike \"/!debug:value\" to set a config property named \"debug\".\r\r\n";

        public const string Site = "Administration of virtual sites\r\r\n\r\r\nAPPCMD (command) SITE <identifier> <-parameter1:value1 ...>\r\r\n\r\r\nSupported commands:\r\r\n\r\r\n  list      List virtual sites\r\n  set       Configure virtual site\r\n  add       Add new virtual site\r\n  delete    Delete virtual site\r\n  start     Start virtual site\r\n  stop      Stop virtual site\r\n\r\r\n(To get help for each command use /?, e.g. 'appcmd.exe add site /?'.)\r\r\n";

        public const string ListApp = "List applications\r\n\r\r\nAPPCMD list APP <identifier> <-parameter1:value1 ...>\r\r\n\r\r\nList the applications on the machine.  This command can be used to find a\r\nspecific application by using its identifier or url, find all applications\r\nbelonging to a specified site or application pool, or match zero or more\r\napplications based on the specified application attributes.\r\n \r\r\nSupported parameters:\r\r\n\r\r\n identifier\r\n\r\n    Application path or url of the application to find\r\n\r\n /app.name\r\n\r\n    Application path or url of the application to find (same as identifier)\r\n\r\n /?\r\n\r\n    Display the dynamic properties that can be used to find one or more\r\n    application objects\r\n\r\n\r\r\nExamples:\r\r\n\r\r\n appcmd list apps\r\n\r\n    List all applications on the machine.\r\n\r\n appcmd list app \"Default Web Site/\"\r\n\r\n    Find the application \"Default Web Site/\" (root application of the site\r\n    \"Default Web Site\").\r\n\r\n appcmd list app http://localhost/app1\r\n\r\n    Find the application associated with the specified url.\r\n\r\n appcmd list apps /site.name:\"Default Web Site\".\r\n\r\n    Find all applications belonging to the site \"Default Web Site\".\r\n\r\n appcmd list apps /apppool.name:\"DefaultAppPool\".\r\n\r\n    Find all applications belonging to the application pool \"DefaultAppPool\".\r\n\r\n appcmd list apps /path:/app1\r\n\r\n    Find all applications that have the \"path\" configuration property set to\r\n    \"/app1\".\r\n\r\n";

        public const string ListVdir = "List virtual directories\r\n\r\r\nAPPCMD list VDIR <identifier> <-parameter1:value1 ...>\r\r\n\r\r\nList the virtual directories on the machine.  This command can be used to find\r\na specific virtual directory by using its identifier or url, find all virtual\r\ndirectories belonging to a specified application, or match zero or more\r\nvirtual directories based on the specified virtual directory attributes.\r\n \r\r\nSupported parameters:\r\r\n\r\r\n identifier\r\n\r\n    Virtual directory path or url of the virtual directory to find\r\n\r\n /vdir.name\r\n\r\n    Virtual directory path or url of the virtual directory to find (same as\r\n    identifier)\r\n\r\n /?\r\n\r\n    Display the dynamic properties that can be used to find one or more\r\n    virtual directory objects\r\n\r\n\r\r\nExamples:\r\r\n\r\r\n appcmd list vdirs\r\n\r\n    List all virtual directories on the machine.\r\n\r\n appcmd list vdir \"Default Web Site/\"\r\n\r\n    Find the virtual directory \"Default Web Site/\" (root virtual directory of\r\n    the root application of the site \"Default Web Site\").\r\n\r\n appcmd list vdir http://localhost/app1\r\n\r\n    Find the virtual directory associated with the specified url.\r\n\r\n appcmd list vdirs /app.name:\"Default Web Site/\".\r\n\r\n    Find all virtual directories belonging to the application \"Default Web\r\n    Site/\".\r\n\r\n appcmd list vdirs /path:/\r\n\r\n    Find all virtual directories that have the \"path\" configuration property\r\n    set to \"/\".\r\n\r\n";

        public const string StartSite = "Start virtual site\r\n\r\r\nAPPCMD start SITE <identifier> <-parameter1:value1 ...>\r\r\n\r\r\nStarts the specified virtual site and enables it to begin listening for new\r\nrequests on all of its binding endpoints.  The exact site identifier must be\r\nprovided and must resolve to an existing site.\r\n \r\r\nSupported parameters:\r\r\n\r\r\n identifier (required)\r\n\r\n    Site name or url of the site to start\r\n\r\n /site.name\r\n\r\n    Site name or url of the site to start (same as identifier)\r\n\r\n\r\r\nExamples:\r\r\n\r\r\n appcmd start site \"Default Web Site\"\r\n\r\n    Start the site \"Default Web Site\".\r\n\r\n";

        public const string ListSite = "List virtual sites\r\n\r\r\nAPPCMD list SITE <identifier> <-parameter1:value1 ...>\r\r\n\r\r\nLists the virtual sites on the machine.  This command can be used to find a\r\nspecific site by using its identifier or url, or match zero or more sites\r\nbased on the specified site attributes.\r\n \r\r\nSupported parameters:\r\r\n\r\r\n identifier\r\n\r\n    Site name or url of the site to find\r\n\r\n /site.name\r\n\r\n    Site name or url of the site to find (same as identifier)\r\n\r\n /?\r\n\r\n    Display the dynamic site properties that can be used to find one or more\r\n    site objects\r\n\r\n\r\r\nExamples:\r\r\n\r\r\n appcmd list sites\r\n\r\n    List all sites on the machine.\r\n\r\n appcmd list site \"Default Web Site\"\r\n\r\n    Find the site \"Default Web Site\".\r\n\r\n appcmd list site http://localhost/app1\r\n\r\n    Find the site associated with the specified url.\r\n\r\n appcmd list site /serverAutoStart:false\r\n\r\n    Find all sites that have the \"serverAutoStart\" configuration property set\r\n    to \"false\".\r\n\r\n";

        public const string RecycleAppPool = "Recycle application pool\r\n\r\r\nAPPCMD recycle APPPOOL <identifier> <-parameter1:value1 ...>\r\r\n\r\r\nRecycles the specified application pool, recycling its the worker processes. \r\nThe exact application pool identifier must be provided and must resolve to an\r\nexisting application pool.\r\n \r\r\nSupported parameters:\r\r\n\r\r\n identifier (required)\r\n\r\n    Application pool name of the application pool to recycle\r\n\r\n /apppool.name\r\n\r\n    Application pool name of the application pool to recycle (same as\r\n    identifier)\r\n\r\n\r\r\nExamples:\r\r\n\r\r\n appcmd recycle apppool \"MyAppPool\"\r\n\r\n    Recycle the application pool \"MyAppPool\".\r\n\r\n";

    }
}
